### ISSUE TITLE
Duplicate comparison logic

### ISSUE THREAD

**Issue by ivanovmg** [haimkastner/unitsnet-py#10]
There is a duplicate comparison logic for every measure entity (methods ``__eq__``, ``__lt__``).
Those could be extracted into a common abstract class ``AbstractMeasure``.

**Comment by haimkastner** [comment]
I think it will not be a good idea to allow compare two different type directly (e.g. Mass VS Length).

Both types can contains value 10, but the meaning of the value if truly different and they don't share the same "value" even it the same number.

Here also I followed the original [UnitsNet](https://github.com/angularsen/UnitsNet) package, where AFAIR this is the behavior, you can compare only Length to Length and not Length to Mass.

This is how [they implemented](https://github.com/angularsen/UnitsNet#convert-between-units-of-custom-quantity) the conversion between two types, you need to define conversion formula, then you can use it to convert, WDYT?

**Comment by ivanovmg** [comment]
Indeed, comparing different types of entities should raise.
In PR #11 I added tests specifically for this reason: ``tests/test_unit_comparing.py``.
Please have a look.

However it is still possible to check for equality.
Length will never be equal to Mass, but this is expected behavior in python:
``` python
>>> 1 == '1'
False
```

**Comment by haimkastner** [comment]
Merged as part of #11
