### ISSUE TITLE
Numpy array support

### ISSUE THREAD

**Issue by ivanovmg** [haimkastner/unitsnet-py#14]
It is impossible to instantiate an object from numpy array due to the check in ``__init__``:
https://github.com/haimkastner/unitsnet-py/blob/670627d586af35d7b799783c9ec34d41065a518c/unitsnet_py/units/volume.py#L293C1-L294D1

Without the check the conversion actually works for numpy arrays, since the operations involved are all compatible with numpy arrays.

I suggest that the check on ``math.isnan`` is removed from the ``__init__``.
Instead the code would be throwing type error during runtime if unable to perform math operations.

**Comment by haimkastner** [comment]
@ivanovmg change merged and released as version [0.1.61](https://pypi.org/project/unitsnet-py/0.1.61/) see PR #15
