### ISSUE TITLE
Python 3.8 support

### ISSUE THREAD

**Issue by ivanovmg** [haimkastner/unitsnet-py#5]
Thank you for the package! This is exactly what I was looking for with units as objects!
However, I would like to use it on my projects using Python 3.8, while your package has lower bound for Python >= 3.10.

It seems to me that the package can easily be extended to support earlier versions of python.
At least, I tried and build the package for Python 3.8 and then was able to install it and use successfully.

I noticed that the code generation section uses type annotations compatible with Python>=3.9 only, but they could simply replaced with 3.8-compatible counterparts, such as ``from typing import List``.

**Comment by haimkastner** [comment]
Implemented by #7
