### ISSUE TITLE
Public method to convert to other unit

### ISSUE THREAD

**Issue by ivanovmg** [haimkastner/unitsnet-py#8]
As a user of this library I would like to use ``Units`` enum explicitly to convert measurements to.

For example:
``` python
length = Length(1, LengthUnits.Meter)
centimeters = length.convert(LengthUnits.Centimeter)
assert centimeters == length.centimeters
```

This is useful when we select the unit to convert to at runtime.

I was thinking of several options to call conversion method.
- ``convert`` - looks OK, probably will be well understood by most users
- ``as`` and ``in`` - probably sound more like plain English (i.e., ``length.in(LengthUnits.Centimeter)``), but these are reserved words in Python
- ``to`` - middle ground between ``convert`` and ``as/in``

**Comment by haimkastner** [comment]
Hi @ivanovmg 

I'm not sure I fully understand the advantage of using convert function with unit as a parameter instead of just `length.centimeters`.


This library is built on top and use the same language as [UnitNet](https://github.com/angularsen/UnitsNet) C# library, and their approach as far as I understand it, is that there is no "conversion" from unit A to unit B, there is just "length" object that you can create from any unit and obtain each unit any time when you need.

**Comment by ivanovmg** [comment]
Sometimes we can only decide which unit to convert to at runtime.
Example:
``` python
def convert(measure, to_unit) -> float:
	...

mapping = {
	'meter': LengthUnits.Meter,
	'foot': LengthUnits.Foot,
	'centimeter': LengthUnits.Centimeter,
}

unit_name= input("Select unit to convert to")  # user input
print(convert(Length.from_meters(1), mapping[unit_name]))
```

The problem is that we cannot figure out the conversion method in general case.
I understand that we can pass the name of the method into the mapping and then call it using ``getattr``, but it seems to be a bit against the grain.

In UnitNet C# implementation they have ``ToUnit`` method.
```
// Assume these are passed in at runtime, we don't know their values or type
Enum userSelectedUnit = LengthUnit.Millimeter;
IQuantity quantity = Length.FromCentimeters(3);

// Later we convert to a unit
quantity.ToUnit(userSelectedUnit).Value;      // 30
quantity.ToUnit(userSelectedUnit).Unit;       // LengthUnit.Millimeter
quantity.ToUnit(userSelectedUnit).ToString(); // "30 mm"
quantity.ToUnit(PressureUnit.Pascal);         // Throws exception, not compatible
quantity.As(userSelectedUnit);                // 30
```

**Comment by haimkastner** [comment]
OK, I see the motivation, merged.
